(icds split) sort dicts by key
This is required for Py3 since dict's don't support the '<'
operator in Py3:

TypeError: '<' not supported between instances of 'dict' and 'dict'