(icds split) switch to full join
ERROR:  cannot run outer join query if join is not on the partition column
DETAIL:  Outer joins requiring repartitioning are not supported.